src/Entity/Offer.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\OfferRepository;
use App\Entity\Traits\Timestampable;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Doctrine\ORM\Mapping\Table;

/**
 * @ORM\Entity(repositoryClass=OfferRepository::class)
 * @ORM\Table(name="offers")
 * @Vich\Uploadable
 * @ORM\HasLifecycleCallbacks
 */
class Offer
{
    use Timestampable;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Length(min=3)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     * @Assert\Length(min=10)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="offers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isAvailable;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, mappedBy="offers")
     */
    private $categories;

    /**
     * @ORM\OneToMany(targetEntity=Picture::class, mappedBy="offer")
     */
    private $pictures;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->pictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getIsAvailable(): ?bool
    {
        return $this->isAvailable;
    }

    public function setIsAvailable(bool $isAvailable): self
    {
        $this->isAvailable = $isAvailable;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->addOffer($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->removeElement($category)) {
            $category->removeOffer($this);
        }

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setOffer($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getOffer() === $this) {
                $picture->setOffer(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use App\Entity\Traits\Timestampable;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping\Table;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="users")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields="email", message="There is already an account with this email")
 */
class User implements UserInterface
{
    use Timestampable;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Please enter your first name")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Please enter your last name")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank(message="Please enter your email address")
     * @Assert\Email(message="Please enter a valid email address")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Offer::class, mappedBy="user", orphanRemoval=true)
     */
    private $offers;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function __construct()
    {
        $this->offers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Offer[]
     */
    public function getoffers(): Collection
    {
        return $this->offers;
    }
    
    public function addOffer(Offer $offer): self
    {
        if (!$this->offers->contains($offer)) {
            $this->offers[] = $offer;
            $offer->setUser($this);
        }

        return $this;
    }

    public function removeOffer(Offer $offer): self
    {
        if ($this->offers->contains($offer)) {
            $this->offers->removeElement($offer);
            // set the owning side to null (unless already changed)
            if ($offer->getUser() === $this) {
                $offer->setUser(null);
            }
        }

        return $this;
    }

    public function getFullName(): string
    {
        return $this->getFirstName() . ' ' . $this->getLastName();
    }

    public function getGravatarUrl(?int $size = 100)
    {
        return sprintf('https://www.gravatar.com/avatar/%s?s=%d', md5(strtolower(trim($this->getEmail()))), $size);
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Form/OfferType.php
<?php

namespace App\Form;

use App\Entity\Offer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Vich\UploaderBundle\Form\Type\VichImageType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class OfferType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            /*->add('imageFile', VichImageType::class, [
                'label' => 'Image (JPG or PNG file)',
                'required' => false,
                'allow_delete' => true,
                'download_uri' => false,
                'imagine_pattern' => 'squared_thumbnail_small'
            ])*/
            ->add('title', TextType::class)
            ->add('description', TextareaType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Offer::class,
        ]);
    }
}

src/Controller/OffersController.php
<?php

namespace App\Controller;

use App\Entity\Offer;
use App\Form\OfferType;
use App\Repository\OfferRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class OffersController extends AbstractController
{
    /**
     * @Route("/", name="app_home")
     */
    public function index(OfferRepository $OfferRepository): Response
    {
        $offers = $OfferRepository->findBy([], ['createdAt' => 'DESC']);

        return $this->render('offers/index.html.twig', compact('offers'));
    }
    
    /**
     * @Route("/offers/create", name="app_offers_create", methods={"GET", "POST"})
     */
    public function create(Request $request, EntityManagerInterface $em, UserRepository $userRepo): Response
    {
        $pin = new Offer;

        $form = $this->createForm(OfferType::class, $pin);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pin->setUser($this->getUser());
            $em->persist($pin);
            $em->flush();

            $this->addFlash('success', 'Offer successfully created!');

            return $this->redirectToRoute('app_home');
        }

        return $this->render('offers/create.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/offers/{id<[0-9]+>}", name="app_offers_show", methods={"GET"})
     */
    public function show(Offer $offer): Response
    {
        return $this->render('offers/show.html.twig', compact('offer'));
    }
    
    /**
     * @Route("/offers/{id<[0-9]+>}/edit", name="app_offers_edit", methods={"GET", "PUT"})
     */
    public function edit(Request $request, Offer $offer, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(OfferType::class, $offer, [
            'method' => 'PUT'
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();

            $this->addFlash('success', 'Offer successfully updated!');

            return $this->redirectToRoute('app_home');
        }

        return $this->render('offers/edit.html.twig', [
            'offer' => $offer,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/offers/{id<[0-9]+>}", name="app_offers_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Offer $pin, EntityManagerInterface $em): Response
    {
        $this->denyAccessUnlessGranted('PIN_MANAGE', $pin);

        if ($this->isCsrfTokenValid('pin_deletion_' . $pin->getId(), $request->request->get('csrf_token'))) {
            $em->remove($pin);
            $em->flush();

            $this->addFlash('info', 'Offer successfully deleted!');
        }

        return $this->redirectToRoute('app_home');
    }
}

templates/offers/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}

<input type="submit" value="{{ submitButtonText ?? 'Create Offer' }}" class="btn btn-primary btn-block" formnovalidate>
{{ form_end(form) }}

templates/offers/create.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title 'New Offer' %}

{% block body %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h1>Create Pin</h1>

            {{ include('offers/_form.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/offers/edit.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title 'Edit Offer #' ~ offer.id %}

{% block body %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h1>Edit Pin #{{ offer.id }}</h1>

            {{ include('offers/_form.html.twig', {'submitButtonText': 'Update Offer'}) }}
        </div>
    </div>
{% endblock %}

templates/offers/index.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title 'Find all the best offers on earth!' %}

{% block body %}
    {% if offers|length > 0 %}
        <h1 class="mb-4 text-center text-muted">{{ pluralize(offers|length, 'Travel Plan') }}</h1>
        
        {% for row in offers|batch(3) %}
            <div class="row mb-5">
            {% for offer in row %}
                <div class="col-md-4">
                    <article class="pin bg-white rounded shadow">
                        <div class="mw-100 rounded-top overflow-hidden">
                            {#<a href="{{ path('app_offers_show', {id: pin.id}) }}">
                                <img src="{{ (pin.imageName ? vich_uploader_asset(pin) : asset('build/images/placeholder.jpg')) | imagine_filter('squared_thumbnail_medium') }}" alt="{{ pin.title }}" class="w-100" />
                            </a>#}
                        </div>
                        <h2 class="h5 pl-3 pt-3"><a href="{{ path('app_offers_show', {id: offer.id}) }}" class="text-secondary text-decoration-none">{{ offer.title }}</a></h2>
                        <p class="pl-3 pb-3 text-muted"><small>Submitted by {{ offer.user.fullName }}</small></p>
                    </article>
                </div>
            {% endfor %}
            </div>
        {% endfor %}
    {% else %}
        <p class="mt-5 h1 text-center">No offers yet. <a href="{{ path('app_offers_create') }}">Be the first!</a></p>
    {% endif %}
{% endblock %}

templates/offers/show.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title offer.title %}

{% block body %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <article class="pin bg-white rounded shadow">
                {#<div class="mw-100 rounded-top overflow-hidden">
                    <img src="{{ (pin.imageName ? vich_uploader_asset(pin) : asset('build/images/placeholder.jpg')) | imagine_filter('squared_thumbnail_medium') }}" alt="{{ pin.title }}" class="w-100" />
                </div>#}

                <div class="p-3">
                    <h1 class="h5 text-secondary">{{ offer.title }}</h1>

                    <p class="text-muted">
                        <small>
                            Submitted 
                            <time datetime="{{ offer.createdAt|date('Y-m-d H:i:s') }}">{{ offer.createdAt|ago }}</time>
                            by {{ offer.user.fullName }}
                        </small>
                    </p>

                    <p class="pt-3 text-break">
                        {{ offer.description }}
                    </p>

                    {#{% if is_granted('PIN_MANAGE', pin) %}#}
                    <div class="pt-3">
                        <a href="{{ path('app_offers_edit', {'id': offer.id}) }}" class="btn btn-light">Edit</a>
                        <a href="#" onclick="event.preventDefault(); confirm('Are you sure?') && document.getElementById('js-pin-delete-form').submit();" class="btn btn-light">Delete</a>

                        <form id="js-pin-delete-form" action="{{ path('app_offers_delete', {id: offer.id}) }}" method="post" style="display: none;">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token('offer_deletion_' ~ offer.id) }}">
                            <input type="hidden" name="_method" value="DELETE">
                        </form> 
                    </div>
                    {#{% endif %}#}
                </div>
            </article>
        </div>
    </div>
{% endblock %}